# Base image
FROM node:18

# Set the working directory
WORKDIR /AUTOMATED-CONTAINER-DEPLOYMENT/Docker/app/

# Copy package.json and yarn.lock (if using Yarn) to the container
COPY app/package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY app .

# Expose the application port (if applicable)
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]
