name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - main  # Trigger deployment on push to main (or your desired branch)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_VM_USERNAME: "adminuser"
      AZURE_VM_IP: "52.233.168.114"
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    # Step 2: Compress the code
    - name: Compress project files
      run: |
        zip -r acd.zip ./*
        ls -la

    # - name: SSH into Azure VM and deploy container
    #   uses: appleboy/ssh-action@v0.1.7
    #   with:
    #     host: ${{ env.AZURE_VM_IP }}
    #     username: ${{ env.AZURE_VM_USERNAME }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     source: "acd.zip"
    #     target: "~/"
        
    # Step 5: Copy Docker image tar to Azure VM using SCP
    - name: Copy your source code to Azure VM
      run: scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} acd.zip ${{ vars.AZURE_VM_USERNAME }}@${{ vars.AZURE_VM_IP }}:/home/${{ vars.AZURE_VM_USERNAME }}/

    - name: Deploy using SCP
      run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* ${{ vars.AZURE_VM_USERNAME }}@${{ vars.AZURE_VM_IP }}: ~/node-app

    # Step 6: SSH into the Azure VM and load the Docker image
    - name: SSH into Azure VM and deploy container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.AZURE_VM_IP }}
        username: ${{ env.AZURE_VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Extract the application files
          unzip acd.zip -d ~/app
          cd ~/app/docker/
          
          # Build the Docker image locally
          docker build -t nextjs-app .
          
          # Stop and remove any existing container (optional)
          docker stop nextjs-container || true
          docker rm nextjs-container || true
          
          # Run the Docker container
          docker run -d --name nextjs-container -p 3000:3000 nextjs-app

          # Optionally restart or perform additional tasks
          echo "Docker container deployed successfully access your application at https://${{ env.AZURE_VM_IP }}:3000"
