name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - main  # Trigger deployment on push to main (or your desired branch)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    # Step 2: Compress the code
    - name: Compress project files
      run: |
        zip -r acd.zip ./*
        ls -la
    # Step 3: Save the SSH private key to a file
    - name: Add SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        
    # Step 5: Copy Docker image tar to Azure VM using SCP
    # - name: Copy your source code to Azure VM
    #   run: scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} acd.zip ${{ vars.AZURE_VM_USERNAME }}@${{ vars.AZURE_VM_IP }}:/home/${{ vars.AZURE_VM_USERNAME }}/

    - name: Deploy using SCP
      run: scp -o StrictHostKeyChecking=no -i ssh_key.pem acd.zip ${{ vars.AZURE_VM_USERNAME }}@${{ vars.AZURE_VM_IP }}:/home/${{ vars.AZURE_VM_USERNAME }}/

    # Step 6: SSH into the Azure VM and load the Docker image
    - name: SSH into Azure VM and deploy container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ vars.AZURE_VM_IP }}
        username: ${{ vars.AZURE_VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Extract the application files
          unzip acd.zip -d ~/app
          cd ~/app/docker/
          
          # Build the Docker image locally
          docker build -t nextjs-app .
          
          # Stop and remove any existing container (optional)
          docker stop nextjs-container || true
          docker rm nextjs-container || true
          
          # Run the Docker container
          docker run -d --name nextjs-container -p 3000:3000 nextjs-app

          # Optionally restart or perform additional tasks
          echo "Docker container deployed successfully access your application at https://${{ env.AZURE_VM_IP }}:3000"
